<?php

return [
    'subjectsUrls' => [
        'mathematics' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/mathematics.html',
        'physicts' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/physics.html',
        'chemistry' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/chemistry.html',
        'earth_sciences' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/earth-sciences.html',
        'geography' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/geography.html',
        'ecology' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/ecology.html',
        'mechanical_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/mechanical-engineering.html',
        'electrical_electronic_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/electrical-electronic-engineering.html',
        'automation_control' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/automation-control.html',
        'telecommunication_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/telecommunication-engineering.html',
        'instruments_science_technology' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/instruments-science-technology.html',
        'biomedical_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/biomedical-engineering.html',
        'computer_science_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/computer-science-engineering.html',
        'civil_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/civil-engineering.html',
        'chemical_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/chemical-engineering.html',
        'materials_science_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/materials-science-engineering.html',
        'nanoscience_nanotechnology' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/nanoscience-nanotechnology.html',
        'energy_science_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/energy-science-engineering.html',
        'environmental_science_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/environmental-science-engineering.html',
        'water_resources' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/water-resources.html',
        'food_science_technology' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/food-science-technology.html',
        'biotechnology' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/biotechnology.html',
        'aerospace_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/aerospace-engineering.html',
        'marine_ocean_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/marine-ocean-engineering.html',
        'transportation_science_technology' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/transportation-science-technology.html',
        'remote_sensing' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/remote-sensing.html',
        'mining_mineral_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/mining-mineral-engineering.html',
        'metallurgical_engineering' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/metallurgical-engineering.html',
        'biological_sciences' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/biological-sciences.html',
        'human_biological_sciences' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/human-biological-sciences.html',
        'agricultural_sciences' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/agricultural-sciences.html',
        'veterinary_sciences' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/veterinary-sciences.html',
        'clinical_medicine' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/clinical-medicine.html',
        'public_health' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/public-health.html',
        'dentistry_oral_sciences' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/dentistry-oral-sciences.html',
        'nursing' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/nursing.html',
        'medical_technology' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/medical-technology.html',
        'pharmacy_pharmaceutical_sciences' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/pharmacy-pharmaceutical-sciences.html',
        'economics' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/economics.html',
        'statistics' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/statistics.html',
        'law' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/law.html',
        'political_sciences' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/political-sciences.html',
        'sociology' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/sociology.html',
        'education' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/education.html',
        'communication' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/communication.html',
        'psychology' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/psychology.html',
        'business_administration' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/business-administration.html',
        'finance' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/finance.html',
        'managment' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/management.html',
        'public_administration' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/public-administration.html',
        'hospitality_tourism_management' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/hospitality-tourism-management.html',
        'library_information_science' => 'http://www.shanghairanking.com/Shanghairanking-Subject-Rankings/library-information-science.html'
    ],
];